---
cluster_admin_group: "cluster-admins"
platform_admin_group: "platform-admins"
platform_user_group: "platform-users"

jumpstarter_admin_group: "jumpstarter-admins"
jumpstarter_user_group: "jumpstarter-users"
