- name: config the RHAS platform
  hosts: localhost
  vars:
    # set the following to control the install/uninstall process
    silent: false
    become_override: false
    ACTION: "INSTALL" # INSTALL, UNINSTALL, UPDATE

  tasks:
    - name: gather cluster facts
      include_role:
        name: roles/gather-cluster-facts

    - name: config the core platform components e.g. devspaces, devhub, etc.
      include_role:
        name: roles/setup-platform